[colors.bright]
black = "#323652"
#blue = "#AECBCD"
#cyan = "#C2D7D4"
blue = "#6A88A9"
cyan = "#9FB3AE"
green = "#A6BA96"
magenta = "#C8A2C1"
red = "#CD664D"
white = "#DFDCCB"
yellow = "#DCDF82"

[colors.normal]
black = "#49463D"
#blue = "#86B7B9"
#cyan = "#9AC3C0"
blue = "#6283B5"
cyan = "#97BEBB"
green = "#579162"
magenta = "#B3816E"
red = "#B95239"
white = "#B7B4A3"
yellow = "#C8B764"

[colors.primary]
#LIGHTMODE
foreground = "#4D4B41"
background = "#DAD3BA"
#DARKMODE
#background = "#4D4B41"
#foreground = "#DAD3BA"

[font]
size = 12
offset = {x=1,y=0}

[font.bold]
#family = "monospace"
family ="FantasqueSansM Nerd Font"
style ="Bold"

[font.normal]
#family = "monospace"
family ="FantasqueSansM Nerd Font"
style = "Regular"

[font.italic]
#family = "monospace"
family ="FantasqueSansM Nerd Font"
style = "Italic"

[font.bold_italic]
#family = "monospace"
family ="FantasqueSansM Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 2000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/bash"

[window]
opacity = 0.8
dynamic_title = false
title = "⬜ Terminal" 

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
